### ISSUE TITLE
Create CloudFormation template to deploy estimation function on AWS via an HTTP endpoint

### ISSUE THREAD

**Issue by brylie** [maasglobal/sustainable-mobility-api#12]
Companies using AWS might prefer to deploy the CO2 estimation endpoints on their infrastructure. We can make this easy by providing a CloudFormation template that deploys the function behind one or more HTTP endpoints, conforming to the specification.

**Comment by huksley** [comment]
Would be a serverless framework instead of SAM/AWS CLI approach good to solve this?

**Comment by brylie** [comment]
Sounds good. I am currently working on creating a Dockerfile for the project so that it can run in any Docker host: #20
