### ISSUE TITLE
Make CO2 calculations based on liters 

### ISSUE THREAD

**Issue by ErikM1995** [maasglobal/sustainable-mobility-api#33]
The API calculates CO2 emission based on mileage per mode of transport and people travelling, which is super useful! However, some platforms (e.g. tank cards) don't have mileage/distance/location information, only how many liters of a certain fuel are tanked. 

Maybe this API could also calculate CO2 emission based on the amount and type of fuel tanked. Data on how much CO2 is emitted per fuel type can be found on https://www.co2emissiefactoren.nl/lijst-emissiefactoren/

p.s.
I don't have any knowledge on coding, so not sure if this is possible to implement, just someone who is passionate about MaaS. 

# Addendum
*This section was added after the initial issue was created, in order to add information and resources related to the task.*

## Resources
- [Ecoscore](https://ecoscore.be/en/info/ecoscore/co2) - describes a method of calculating CO2 emissions per litre of petrol and diesel
- [table of CO2 emissions by fuel](https://people.exeter.ac.uk/TWDavies/energy_conversion/Calculation%20of%20CO2%20emissions%20from%20fuels.htm) without mention of source or methodology (may still prove useful)
- Natural Resources Canada published a [fact sheet estimating CO2 kg/L for several fuels](https://www.nrcan.gc.ca/sites/www.nrcan.gc.ca/files/oee/pdf/transportation/fuel-efficient-technologies/autosmart_factsheet_6_e.pdf) - namely petrol, diesel, biodiesel, and ethanol
- [IPCC emissions factors database](https://www.ipcc-nggip.iges.or.jp/EFDB/main.php) has extensive data on [road transportation fuel combustion activities](https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php?ipcc_code=1.A.3.b&ipcc_level=3)
- U.S. Environmental Protection Agency published [CO2 emissions metrics for gasoline and diesel combustion](https://www.epa.gov/energy/greenhouse-gases-equivalencies-calculator-calculations-and-references) as well as a [greenhouse gas equivalencies calculator](https://www.epa.gov/energy/greenhouse-gas-equivalencies-calculator)

**Comment by MarkusShepherd** [comment]
That sounds very interesting and useful to me. I see two ways to calculate the CO2 emission by litre of fuel:

1. Obtaining the numbers of emission by volume of fuel. In many respects that should be easy and fairly accurate as that's the very source of CO2 being emitted.
2. If we use average km/l or miles/gallons numbers for cars, we can convert the fuel volume into distance travelled, and plug this into our model as-is.

**Comment by brylie** [comment]
@ErikM1995, thanks for the suggestion. I am taking a more in-depth look into this idea now. I will post my findings as comments here so that we can discuss things like the data sources/model and API.

**Comment by brylie** [comment]
@MarkusShepherd in terms of Python architecture, would we perhaps create a new class like `CO2_Estimator` that handles mode- and fuel-based estimations?

**Comment by brylie** [comment]
Relatedly, Transport and Environment published an interactive article today called "[How clean are electric cars?](https://www.transportenvironment.org/news/how-clean-are-electric-cars)".

> To answer this question we have developed a tool (see below) that compiles all the most up-to-date data on CO2 emissions linked to the use of an electric, diesel or petrol car.

We might be able to dig into their source data for our purposes.

**Comment by MarkusShepherd** [comment]
> @MarkusShepherd in terms of Python architecture, would we perhaps create a new class like `CO2_Estimator` that handles mode- and fuel-based estimations?

What would that class look like? I'm not sure I see a benefit in a class that just throws different purposes together.

If we want to have one unified way to calculate emissions (and we'd first need to convince ourselves that's something useful), the best way I see is to change the `estimator.estimate_co2()` signature to

```python
def estimate_co2(**kwargs) -> float:
    # do something
```

and then select the lower level functionality depending on what arguments were passed. But right now I'd say it'll only obscure the API, so if distance and fuel based estimates are the only two use cases, why not just have two different methods or classes to call?

**Comment by brylie** [comment]
So for now, just defining a new function like `estimate_co2_from_fuel_consumed(fuel_type, volume, units)`?

**Comment by MarkusShepherd** [comment]
Yeah, more or less. I'd think analogous to `Mode` we could create a class `Fuel`, an `Enum` with different instances like `PETROL`, `DIESEL`, `LPG` (?), and field `avg_co2_per_liter`.

As for the method API, I don't like these overly long names (just couldn't be bothered to read all that stuff), so would rather have something like `estimator.from_distance()` and `estimator.from_fuel()` or similar. Not a hill I'm willing to die on though... 😉

**Comment by brylie** [comment]
I fully agree with everything you say above, which is why I am asking you about the API design ;-)

**Comment by MarkusShepherd** [comment]
Hmmm... I've stumbled across the question of units for fuel calculations. Some are measured by volume (litres, gallons, cubic metres, ...), while others are measured by mass (kg, tonne, whatever Americans use). Then there's electricity of course that's measure directly in energy... You noted the unit in some example above, but at that point I only thought of litres vs gallons, not volume vs mass.

So we would need `co2_per_unit` and `unit` for each fuel type, plus potentially some conversions between units. Also, it would be great to link `Mode` and `Fuel` via litres/km (or miles/gallon for the metrically challenged 😜).

Sorry, turned out a bit of rambling, seems like there's quite a number of use cases that need to be considered...

**Comment by brylie** [comment]
OK. Do you know of a good Python library we can lean on for unit conversion?

**Comment by brylie** [comment]
Also for starters, I was planning to use these metrics:

![image](https://user-images.githubusercontent.com/17307/79963524-33f4e300-8492-11ea-811a-e1edd526f0b5.png)

**Comment by brylie** [comment]
@ErikM1995 we have a pull request open (#43) now that will hopefully fulfil your feature request! :-)

**Comment by ErikM1995** [comment]
Wow, nice work guys! Great to see that you really took the time to think about the possibilities of this idea. About the units of measurement, I always use https://www.co2emissiefactoren.nl/lijst-emissiefactoren/ . This is a pretty good databank formed by the Dutch ministry of economics and environment and some energy companies, but unfortunately that's in Dutch. Many of the fuel names are in English though.

They also open up the debate whether you'd want to incorporate the well to wheel, well to tank or tank to wheel CO2 ratio, interesting stuff!
