### ISSUE TITLE
Allow developers to override model parameters

### ISSUE THREAD

**Issue by brylie** [maasglobal/sustainable-mobility-api#5]
Our library currently uses hard-coded formulas to calculate CO2 emissions based on vehicle averages. Some transport providers may have specific data on the CO2 emissions per passenger kilometer for their fleet. So, they would get more accurate estimations if they could tweak the parameter values when estimating CO2.

## Task
- developers can override all parameters used in CO2 calculation
- parameters have sensible defaults
- defaults are based on an existing CO2 emissions model
- project documentation includes reference to the underlying CO2 model used for defaults

**Comment by MarkusShepherd** [comment]
I'd think we should add more parameters to `Mode.estimate_co2()`, in this case `co2_per_vehicle_km` with default `None`, which then gets replaced with the value as defined by the mode, analogous to `occupancy`.

This approach could get a little clunky as we add more parameters to the model, but I think it'll be manageable and transparent what factors play a role in our model.

**Comment by MarkusShepherd** [comment]
The signature could look something like this:
```python
estimate_co2(
    distance_in_km: float, *, 
    co2_per_vehicle_km: Optional[float] = None,
    occupancy: Optional[float] = None,
) -> float
```
The `*` in the arg list means we can add more parameters more easily in the future as they won't break backward compatibility.

**Comment by brylie** [comment]
How would this API be used consistently with an estimation based on liters of fuel (issue #33)?

**Comment by MarkusShepherd** [comment]
I've pushed the suggested change to #40, let me know if you agree to this approach.

I've been thinking about how this connects to #33. My conclusion is that this suggestion is sufficiently different from the mode based estimates that we now use, so it makes no sense to force it into the same API as `Mode.estimate_co2()`.

It might make sense to have a unified API in `estimator.estimate_co2()` that allows both distance and fuel based estimates, in which case I'd say the `*` "moves up":

```python
def estimate_co2(
    *,
    mode: Union[str, Mode, None] = None,
    distance_in_km: Optional[float] = None,
    fuel_liters: Optional[float] = None,
    co2_per_vehicle_km: Optional[float] = None,
    occupancy: Optional[float] = None
) -> float:
    pass
```

Then we would have to check inside the method what case we're in, resolve parameters reasonably, and raise exceptions if they are insufficient. Also, we'd really need to know what kind of fuel we're talking about. So in conclusion, we should probably just make it a separate call.
